/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_VGMStreamPlugin */

#ifndef _Included_com_ssb_droidsound_plugins_VGMStreamPlugin
#define _Included_com_ssb_droidsound_plugins_VGMStreamPlugin
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_setOption
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1setOption
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_load
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1load
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_loadFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1loadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1getSoundData
  (JNIEnv *, jobject, jlong, jshortArray, jint);
  
/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1getFrameRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_getStringInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1getStringInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VGMStreamPlugin
 * Method:    N_getIntInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_VGMStreamPlugin_N_1getIntInfo
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
